#------------------------
# Header config
title: Liarlee's Notebook
author: Liarlee
# put the logo on the ${blog_path}/source/img/${picname}.png or use urls
logo_img: /img/logo.png
author_img: /img/avatar.jpg
# author_description: designed by theme-kaze
#------------------------
# Navbar config
#------------------------
menus:
  home: /
  archive: /archives
  tags: /tags
  categories: /categories
  about: /about
  friends: /links
  # artitalk: /shuoshuo # You can uncomment to add this route

about:
  description: description
  social_links:
    # - { icon: icon, link: your link }

#------------------------
# Links
#------------------------
links:
  Martin:
    url: http://martinhan.com
    avatar: http://martinhan.com/img/avatar_trans.png
    description: BigBrother
  zhaojiew:
    url: https://blog.csdn.net/sinat_41567654
    avatar: http://profile-avatar.csdnimg.cn/f4560f1218dc473fa5a077d24825ba81_sinat_41567654.jpg!1
    description: DEP 卷王
  #------------------------
  # tip: if you want to use QQ avatar without giving away your QQ number,
  # you can use this api to get an encrypted url:
  # https://ptlogin2.qq.com/getface?appid=1006102&imgtype=3&uin=${yourQQNumber}
  # and use the encrypted url in the json
  #------------------------

#------------------------
# animation config
#------------------------
# if scrollUpAnimation is true, there will be scroll-up animation.
scrollUpAnimation: true

#------------------------
# Footer
#------------------------
footer:
  copyYear: 2017
  # if showPoweredBy is ture, 'Powered by Hexo' will be seen on the footer
  showPoweredBy: true
  # if showThemeName is ture, 'Theme - Kaze' will be seen on the footer
  showThemeName: true
  #------------------------
  # Record config
  # please put the gov image in ${yoursite}/img/beian.png
  RecordInfo: "" # your Record info such as '某ICP备xxx号'
  govRecordInfo: "" # your gov record info such as '某公网安备xxx号'
  govRecordUrl: "" # your gov record url
  #------------------------
  # pv / uv statistics config
  #------------------------
  statistics:
    enable: false
    type: busuanzi # now version only supports busuanzi
    pv:
      enable: true
      style: 本站总访问量{}次 # the style will be shown as $1{pv}$2
    uv:
      enable: true
      style: 本站总访客数{}次 # the style will be shown as $1{uv}$2

#------------------------
# Post
#------------------------
toc:
  showListNumber: false
  maxDepth: 6
  minDepth: 1

copyright:
  enable: true
  writer: # if writer is empty we will use config.author as writer
  declare: 本博客所有文章除特别声明外，均采用<a target="_blank" rel="noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh">CC BY-NC-SA 4.0 协议</a>。转载请注明出处！
  style: warning # the style uses note warning | danger | primary | info | success

search:
  enable: true
  path: search.json
  field: all
  searchContent: true

og:
  enable: true
  title: true
  url: true
  image: true
  description: true
  article: true

# If your hexo version is below 5.0.0, please upgrade first to use this config
# we support eight highlight themes, you can go to prism website (https://prismjs.com) for more information
# theme: default | coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
prism:
  theme: okaidia
  darkTheme: okaidia
# show the number of words in posts
wordcount:
  enable: true

#------------------------
# lazyload config
#------------------------
lazyload:
  enable: true
  loadingImg:

#------------------------
# theme design config
#------------------------
# the config of theme colors and styles
# you can modify these presets to design different styles
color:
  text-color: "#3c4858"
  text-strong-color: "#2f3d4e"
  text-light-color: "#60656a"
  divider-color: "#e6e8ee"
  title-color: "#475b6d"
  link-color: "#3273dc"
  link-hover-color: "#6596e5"
  info-text-color: "#60656a"
  widget-background-color: "#fff"
  body-background-color: "#f2f5f8"
  border-color: "#e1e4e9"
  pre-color: "#2d2d2d"
  code-color: "#50687c"
  code-background-color: "#e9eaf0"

font:
  font-size: 16px # global font-size
  font-family: 'sans-serif,"PingFang SC",-apple-system,BlinkMacSystemFont,"Segoe UI","Helvetica Neue","Microsoft YaHei",sans-serif' # global font-family

#------------------------
# cdn config
#------------------------
cdn:
  mathjax: //cdn.jsdelivr.net/npm/mathjax@3.0.5/es5/tex-svg.js
  katex: //cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css
  gitalk:
    css: //cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
    js: //cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js
  valine: //unpkg.com/valine/dist/Valine.min.js
  livere: //cdn-city.livere.com/js/embed.dist.js
  waline: 
    js: //unpkg.com/@waline/client@v2/dist/waline.js
    css: //unpkg.com/@waline/client@v2/dist/waline.css
  baguetteBox: /js/lib/lightbox
  lozad: /js/lib/lozad.min.js
  prism: /js/lib/prism/
  busuanzi: /js/lib/busuanzi.min.js
  artitalk: https://cdn.jsdelivr.net/npm/artitalk
  md5: /js/lib/md5.min.js
